### PR TITLE
Fixing verdict schemas

### LINKED ISSUE #133: Verdict and StoredVerdict should follow the standard pattern
Most entities have an :id and :schema-version fields, which are mixed in with base-entity-entries.  Verdict is an exception to this, but it shouldn't be.  It should be treated like any other entity.  Instead, StoredVerdict adds those fields.  This causes problems in CTIA because we want to be able to convert a StoredVerdict into a Verdict by stripping off standard store keys.

Make Verdict and StoredVerdict conform to the common pattern.

### PR DESCRIPTION
**Pull request by polygloton**
Closes #133

### CODE REVIEW

File: project.clj [hunk 1]
```diff
@@ -1,7 +1,7 @@
 (def schema-tools-version "0.9.0")
 (def schema-version "1.1.3")
 
-(defproject threatgrid/ctim "0.4.3"
+(defproject threatgrid/ctim "0.4.4-SNAPSHOT"
```
Comment (quoll) [inline project.clj]: Is this the correct PR to be updating the version to SNAPSHOT? I presume that the version update is just piggy-backing on this PR

Comment (polygloton) [inline project.clj]: The change will require a new version.  The alternative is to bump the version directly in master, which I'm fine doing, but I'm also fine doing it in the PR.
